title: Zettel Notes Documentation
email: info@thedoc.eu.org
description: >- # this means to ignore newlines until "baseurl:"
  Documentation for Zettel Notes : Markdown note taking app for android
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  damionx7

# Aux links for the upper right navigation
aux_links:
  "Contribute on GitHub!":
    - "https://github.com/damionx7/Zettel-Notes-Documentation/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_repository: "https://github.com/damionx7/Zettel-Notes-Documentation" # the github URL for your repo

# Build settings
theme: "just-the-docs"
#remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
